Added s7.graph module which includes functions to fetch subgraphs
SINTEF/soft7 pull request #33
Opened 2024-07-02 08:30 UTC by quaat

Added utility module for fetching sub-graphs from triplestores.

2024-07-02 08:43 UTC, CasperWA commented on graph/utils.py
> +        print(f"Jinja2 template error: {e}")
```suggestion
        print(f"Jinja2 template error: {e}", file=sys.stderr)
```

2024-07-02 08:43 UTC, CasperWA commented on graph/utils.py
> +    print("Could not find a common parent node.")
```suggestion
    print("Could not find a common parent node.", file=sys.stderr)
```

2024-07-02 08:43 UTC, CasperWA commented on graph/utils.py
> +
```suggestion

import sys

```

2024-07-02 08:45 UTC, CasperWA commented on graph/utils.py
> +) -> rdflib.Graph:
```suggestion
) -> rdflib.Graph | None:
```

2024-07-02 08:47 UTC, CasperWA commented on graph/utils.py
> +            g.add((s, p, o))
```suggestion
            graph.add(
                (
                    rdflib.URIRef(result["subject"]["value"]),
                    rdflib.URIRef(result["predicate"]["value"]),
                    rdflib.URIRef(result["object"]["value"]),
                )
            )
```

2024-07-02 08:47 UTC, CasperWA commented on graph/utils.py
> +    g = rdflib.Graph()
```suggestion
    graph = rdflib.Graph()
```

2024-07-02 08:47 UTC, CasperWA commented on graph/utils.py
> +    return g
```suggestion
    return graph
```

2024-07-02 08:47 UTC, CasperWA commented on graph/utils.py
> +        print(f"Failed to fetch or parse results: {e}")
```suggestion
        print(f"Failed to fetch or parse results: {e}", file=sys.stderr)
```

2024-07-02 11:02 UTC, quaat commented on graph/utils.py
> +    print("Could not find a common parent node.")
Re-raising exceptions as RuntimeError

2024-07-03 08:53 UTC, CasperWA commented on graph/README.md
> +Ancestor` (LCA) of a set of classes and to populate an RDF graph with
Just out of curiosity - is "Lowest Common Ancestor" a normal/regular expression used here? Mainly because LCA is already an acronym for sooo many things 😅

2024-07-03 09:00 UTC, CasperWA requested changes

2024-07-03 09:00 UTC, CasperWA commented on graph/README.md
> +	pip install rdflib SPARQLWrapper jinja2
```suggestion
pip install rdflib SPARQLWrapper jinja2
```

2024-07-03 09:00 UTC, CasperWA commented on graph/README.md
> +
```suggestion

Or you can install the SOFT7 package with the `graph` extra:

```bash
cd ..
pip install .[graph}
\```

```

Remember to remove the backwards slash here as I needed to add it to not screw up the internal markdown in this comment.

2024-07-03 09:00 UTC, CasperWA commented on graph/README.md
> +  * **sparql (SPARQLWrapper)**: An instance of SPARQLWrapper * configured for the target SPARQL service.
```suggestion
  * **sparql (SPARQLWrapper)**: An instance of SPARQLWrapper configured for the target SPARQL service.
```

2024-07-03 09:00 UTC, CasperWA commented on graph/utils.py
> +        rdflib.Graph: The graph populated with the fetched triples.
```suggestion
        Optional[rdflib.Graph]: The graph populated with the fetched triples.
```

2024-07-04 11:25 UTC, quaat commented on graph/README.md
> +Ancestor` (LCA) of a set of classes and to populate an RDF graph with
It is indeed used in litterature on the topic of topology and common ancestor search algorithms for semantic similarities etc.

2024-07-04 11:29 UTC, merged